import tkinter
root = tkinter.Tk()
root.geometry('400x200+100+200')
l1=tkinter.Label(root, text="Number Addition Program",font="Arial 18 bold")
l2=tkinter.Label(root, text="First No:")
l3=tkinter.Label(root, text="Second No:")
e1=tkinter.Entry(root)
e2=tkinter.Entry(root)
b1=tkinter.Button(root,text="Add")
b2=tkinter.Button(root,text="Clear")
b3=tkinter.Button(root,text="Quit")
l1.grid(row=0,column=0)
l2.grid(row=1,column=0,sticky=tkinter.E)
e1.grid(row=1,column=1,columnspan=2)
l3.grid(row=2,column=0,sticky=tkinter.E)
e2.grid(row=2,column=1)
b1.grid(row=3,column=0,pady=5,padx=5,sticky=tkinter.E+tkinter.W)
b2.grid(row=3,column=1,pady=5,padx=5,sticky=tkinter.E+tkinter.W)
b3.grid(row=3,column=2,pady=5,padx=5,sticky=tkinter.E+tkinter.W)
root.mainloop()
