import tkinter
root = tkinter.Tk()
lbl0 = tkinter.Label(root,text = "Name:")
lbl1 = tkinter.Label(root,text = "Password:")
e1 = tkinter.Entry(root)
e2 = tkinter.Entry(root)
c1 = tkinter.Checkbutton(root,text ="keep me logged in ")
b1 = tkinter.Button(root,text = "login")
b2 = tkinter.Button(root,text = "Quit")
lbl0.grid(row = 0 ,column = 0)
e1.grid(row = 0 ,column = 1,sticky = tkinter.E)
lbl1.grid(row = 1 ,column = 0,columnspan = 2)
e2.grid(row = 1 ,column = 1)
b1.grid(row = 2 , column = 0 ,sticky = tkinter.W + tkinter.E)
b2.grid(row = 2,column = 1,sticky = tkinter.W + tkinter.E)
root.mainloop()
